CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    numero_carne VARCHAR(255) UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    prestamos_activos INTEGER NOT NULL
        DEFAULT 0
);

CREATE TABLE usuario_prestamos_registrados (
    usuario_id BIGINT NOT NULL
        REFERENCES usuarios (id),
    prestamo_id BIGINT NOT NULL
);
