spring.application.name=servicio-libros
server.port=8081

spring.config.import=\
  optional:configserver:http://localhost:8888

spring.datasource.url=jdbc:h2:mem:libros_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

eureka.client.service-url.defaultZone=\
  http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=servicio-libros
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=\
  org.apache.kafka.common.serialization.\
  StringDeserializer
spring.kafka.consumer.value-deserializer=\
  org.springframework.kafka.support.serializer.\
  JsonDeserializer
spring.kafka.consumer.properties.spring.json.\
  trusted.packages=com.biblioteca.libros.evento
spring.kafka.consumer.properties.spring.json.\
  value.default.type=\
  com.biblioteca.libros.evento.PrestamoEvento
spring.kafka.consumer.properties.spring.json.\
  use.type.headers=false
spring.kafka.producer.key-serializer=\
  org.apache.kafka.common.serialization.\
  StringSerializer
spring.kafka.producer.value-serializer=\
  org.springframework.kafka.support.serializer.\
  JsonSerializer
