CREATE TABLE libros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) NOT NULL,
    anio_publicacion INTEGER NOT NULL,
    disponible BOOLEAN NOT NULL DEFAULT TRUE,
    prestamo_reserva_id BIGINT
);
