CREATE TABLE outbox_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    prestamo_id BIGINT NOT NULL,
    libro_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    fecha_evento TIMESTAMP NOT NULL,
    procesado BOOLEAN NOT NULL DEFAULT FALSE
);
