spring.application.name=servicio-prestamos
server.port=8083

spring.config.import=\
  optional:configserver:http://localhost:8888

spring.datasource.url=jdbc:h2:mem:prestamos_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

eureka.client.service-url.defaultZone=\
  http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

feign.client.config.default.logger-level=basic
logging.level.com.biblioteca.prestamos.cliente=DEBUG

resilience4j.circuitbreaker.instances.\
  servicio-libros.sliding-window-size=10
resilience4j.circuitbreaker.instances.\
  servicio-libros.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.\
  servicio-libros.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.\
  servicio-libros.ignore-exceptions=\
  feign.FeignException.NotFound

resilience4j.circuitbreaker.instances.\
  servicio-usuarios.sliding-window-size=10
resilience4j.circuitbreaker.instances.\
  servicio-usuarios.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.\
  servicio-usuarios.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.\
  servicio-usuarios.ignore-exceptions=\
  feign.FeignException.NotFound

resilience4j.retry.instances.servicio-libros.\
  max-attempts=3
resilience4j.retry.instances.servicio-libros.\
  wait-duration=500ms
resilience4j.retry.instances.servicio-libros.\
  ignore-exceptions=feign.FeignException.NotFound

resilience4j.retry.instances.servicio-usuarios.\
  max-attempts=3
resilience4j.retry.instances.servicio-usuarios.\
  wait-duration=500ms
resilience4j.retry.instances.servicio-usuarios.\
  ignore-exceptions=feign.FeignException.NotFound

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=\
  org.apache.kafka.common.serialization.\
  StringSerializer
spring.kafka.producer.value-serializer=\
  org.springframework.kafka.support.serializer.\
  JsonSerializer
